apiVersion: apps/v1
kind: Deployment
metadata:
  name: petshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petshop
  template:
    metadata:
      labels:
        app: petshop
    spec:
      containers:
        - name: petshop
          image: sherlin1595/petshop:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: petshop
spec:
  type: LoadBalancer
  selector:
    app: petshop
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
